#pragma once

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CUSTOM_EFFECT1
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

// Space Cadet ALT keys
#define LAPO_KEYS KC_LEFT_ALT, KC_LEFT_SHIFT, KC_LBRC
#define RAPC_KEYS KC_RIGHT_ALT, KC_RIGHT_SHIFT, KC_RBRC

